"""Diccionario manual de gestoras COMERCIALES catalanas conocidas.

El RGPGRC scrapeado contiene mayoritariamente INSTALACIONES físicas (plantas,
dipòsits, deixalleries), NO empresas comerciales propietarias que prestan
servicio a productores industriales.

Este diccionario complementa el dataset con las empresas comerciales más
relevantes del sector catalán. Ampliable: cada vez que el cliente pregunta
por una gestora que no aparece, añadirla aquí con sus datos públicos.

Fuentes:
- Web pública de cada gestora
- gestoresderesiduos.org
- Memoria EMAS / informes públicos
- Conocimiento del sector
"""

from __future__ import annotations

# Cada entry: nombre comercial → datos públicos
GESTORAS_COMERCIALES_CAT: list[dict] = [
    # ── Recogida y gestión integral de residuos peligrosos ──
    {
        "nom": "GERCO (Gestión de Residuos Contaminantes)",
        "razon_social": "GESTIÓN DE RESIDUOS CONTAMINANTES, SL",
        "nif": "B60866803",
        "poblacio": "GRANOLLERS",
        "comarca": "Vallès Oriental",
        "lat": 41.6038,
        "lon": 2.2891,
        "ambit": "Cataluña",
        "categoria": "ESP",  # residuos especiales
        "tipo": "comercial_privada",
        "tipos_residuo": "Peligrosos y no peligrosos — almacenamiento, transporte, eliminación",
        "web": "https://residuosgerco.com",
    },
    {
        "nom": "GERCO (Gerco Gestión de Residuos SLU)",
        "razon_social": "GERCO GESTIÓN DE RESIDUOS, SLU",
        "nif": "B44659928",
        "poblacio": "GRANOLLERS",
        "comarca": "Vallès Oriental",
        "lat": 41.6080,
        "lon": 2.2917,
        "ambit": "Cataluña",
        "categoria": "ESP",
        "tipo": "comercial_privada",
        "tipos_residuo": "CRT - Centro Recogida y Transferencia + Valorización",
        "web": "https://residuosgerco.com",
    },
    {
        "nom": "TRARGISA (Tractament Residus i Aigües Industrials Selectius)",
        "razon_social": "TRARGISA, SA",
        "nif": "A17001616",
        "poblacio": "LLORET DE MAR",
        "comarca": "Selva",
        "lat": 41.7165,
        "lon": 2.8420,
        "ambit": "Cataluña",
        "categoria": "ESP",
        "tipo": "comercial_privada",
        "tipos_residuo": "Tratamiento residuos especiales + lodos + aguas industriales",
        "web": "https://www.trargisa.com",
    },
    {
        "nom": "FERIMET (Granollers)",
        "razon_social": "FERIMET, SLU",
        "nif": "B58029877",
        "poblacio": "GRANOLLERS",
        "comarca": "Vallès Oriental",
        "lat": 41.6042,
        "lon": 2.2880,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",  # Grupo CELSA
        "tipos_residuo": "Chatarra férrica + descontaminación VFU + metales",
        "web": "https://ferimet.com",
    },
    {
        "nom": "FERIMET (La Selva del Camp)",
        "razon_social": "FERIMET, SLU",
        "nif": "B58029877",
        "poblacio": "LA SELVA DEL CAMP",
        "comarca": "Baix Camp",
        "lat": 41.2117,
        "lon": 1.1394,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Chatarra + metales no férricos",
        "web": "https://ferimet.com",
    },
    {
        "nom": "PreZero España",
        "razon_social": "PREZERO ESPAÑA, SAU",
        "nif": "A48140918",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Recogida, transporte, tratamiento y valorización integral",
        "web": "https://www.prezero.com/es",
    },
    {
        "nom": "URBASER (Servicios Cataluña)",
        "razon_social": "URBASER, SA",
        "nif": "A79524054",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "España",
        "categoria": "MUN",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Recogida selectiva, limpieza urbana, gestión integral",
        "web": "https://www.urbaser.com",
    },
    {
        "nom": "FCC Medio Ambiente",
        "razon_social": "FCC MEDIO AMBIENTE, SAU",
        "nif": "A28541639",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "España",
        "categoria": "MUN",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Limpieza urbana, recogida selectiva, gestión integral",
        "web": "https://www.fcc.es",
    },
    {
        "nom": "Veolia Servicios Norte",
        "razon_social": "VEOLIA SERVICIOS NORTE, SA",
        "nif": "A28076458",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Tratamiento residuos peligrosos + aguas industriales",
        "web": "https://www.veolia.es",
    },
    {
        "nom": "Befesa Aluminio (Les Franqueses)",
        "razon_social": "BEFESA ALUMINIO, SL",
        "nif": "B61006649",
        "poblacio": "LES FRANQUESES DEL VALLÈS",
        "comarca": "Vallès Oriental",
        "lat": 41.6294,
        "lon": 2.2818,
        "ambit": "Cataluña",
        "categoria": "ESP",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Reciclaje aluminio + residuos peligrosos metalúrgicos",
        "web": "https://www.befesa.com",
    },
    {
        "nom": "SAICA Natur (Zona Franca)",
        "razon_social": "SAICA NATUR, SL",
        "nif": "B50447011",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3331,
        "lon": 2.1271,
        "ambit": "España",
        "categoria": "RUN",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Papel, cartón, plástico, recuperación",
        "web": "https://www.saicanatur.com",
    },
    {
        "nom": "Hermanos Lebrero (Castellbisbal)",
        "razon_social": "HERMANOS LEBRERO, SA",
        "nif": "A08015497",
        "poblacio": "CASTELLBISBAL",
        "comarca": "Vallès Occidental",
        "lat": 41.4760,
        "lon": 1.9847,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Áridos reciclados + RCD construcción y demolición",
        "web": "https://www.hermanoslebrero.com",
    },
    {
        "nom": "Recuperaciones Marcel Navarro i Fills",
        "razon_social": "RECUPERACIONS MARCEL NAVARRO I FILLS, SL",
        "nif": "B25024540",
        "poblacio": "JUNEDA",
        "comarca": "Garrigues",
        "lat": 41.5494,
        "lon": 0.8275,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Chatarra metálica + VFU + RAEE",
        "web": "https://www.marcelnavarro.com",
    },
    {
        "nom": "Hierros Soria (Castellbisbal)",
        "razon_social": "HIERROS SORIA, SL",
        "nif": "B58116005",
        "poblacio": "CASTELLBISBAL",
        "comarca": "Vallès Occidental",
        "lat": 41.4762,
        "lon": 1.9849,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Chatarra + metales no férricos + VFU",
        "web": "https://hierrossoria.com",
    },
    {
        "nom": "Hierros Albir (Sant Pere de Vilamajor)",
        "razon_social": "HIERROS ALBIR, SL",
        "nif": "B58044570",
        "poblacio": "SANT PERE DE VILAMAJOR",
        "comarca": "Vallès Oriental",
        "lat": 41.6864,
        "lon": 2.3933,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Chatarra metálica + RAEE",
        "web": "",
    },
    {
        "nom": "Ecocat (Recogida selectiva)",
        "razon_social": "ECOCAT, SL",
        "nif": "B58898123",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "Cataluña",
        "categoria": "ESP",
        "tipo": "comercial_privada",
        "tipos_residuo": "Recogida selectiva residuos peligrosos industriales",
        "web": "https://www.ecocat.com",
    },
    {
        "nom": "Industrial Química Cucurny",
        "razon_social": "INDUSTRIAL QUÍMICA CUCURNY, SA",
        "nif": "A08252504",
        "poblacio": "TERRASSA",
        "comarca": "Vallès Occidental",
        "lat": 41.5635,
        "lon": 2.0086,
        "ambit": "Cataluña",
        "categoria": "ESP",
        "tipo": "comercial_privada",
        "tipos_residuo": "Disolventes + residuos químicos + gestión integral",
        "web": "https://cucurny.com",
    },
    {
        "nom": "Cespa Compañía Española de Servicios Públicos Auxiliares",
        "razon_social": "CESPA, COMPAÑÍA ESPAÑOLA DE SERVICIOS PÚBLICOS AUXILIARES, SA",
        "nif": "A82741067",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "España",
        "categoria": "MUN",
        "tipo": "comercial_privada_multinacional",  # Grupo Ferrovial
        "tipos_residuo": "Limpieza viaria + recogida + gestión integral",
        "web": "https://www.ferrovial.com",
    },
    {
        "nom": "Sociedad Recuperación Materias Primas (Granollers)",
        "razon_social": "SOCIEDAD RECUPERACIÓN MATERIAS PRIMAS, SLU",
        "nif": "B66023303",
        "poblacio": "GRANOLLERS",
        "comarca": "Vallès Oriental",
        "lat": 41.6049,
        "lon": 2.2890,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Recuperación + reciclaje materiales",
        "web": "",
    },
    {
        "nom": "Stericycle España",
        "razon_social": "STERICYCLE SPAIN, SL",
        "nif": "B30495395",
        "poblacio": "MOLLET DEL VALLÈS",
        "comarca": "Vallès Oriental",
        "lat": 41.5419,
        "lon": 2.2131,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Residuos sanitarios + biológicos + peligrosos hospitalarios",
        "web": "https://www.stericycle.com/es-es",
    },
    {
        "nom": "Consenur (residuos sanitarios)",
        "razon_social": "CONSENUR, SA",
        "nif": "A28538189",
        "poblacio": "MARTORELLES",
        "comarca": "Vallès Oriental",
        "lat": 41.5293,
        "lon": 2.2456,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Residuos sanitarios grupo III/IV + biopeligrosos",
        "web": "https://www.consenur.com",
    },
    {
        "nom": "Recuperación Industriales Iberica (Vilanova i la Geltrú)",
        "razon_social": "RECUPERACIÓN INDUSTRIALES IBERICA, SL",
        "nif": "B62076625",
        "poblacio": "VILANOVA I LA GELTRÚ",
        "comarca": "Garraf",
        "lat": 41.2241,
        "lon": 1.7259,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Recuperación industriales + metales",
        "web": "",
    },
    {
        "nom": "Hera Holding (Tractament integral)",
        "razon_social": "HERA TRATESA, SA",
        "nif": "A58124926",
        "poblacio": "VACARISSES",
        "comarca": "Vallès Occidental",
        "lat": 41.6049,
        "lon": 1.9173,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada",
        "tipos_residuo": "Tratamiento integral RP + RNP + valorización energética",
        "web": "https://www.heraholding.com",
    },
    {
        "nom": "Atlas Gestión Medioambiental",
        "razon_social": "ATLAS GESTIÓN MEDIOAMBIENTAL, SAU",
        "nif": "A50769430",
        "poblacio": "MARTORELL",
        "comarca": "Baix Llobregat",
        "lat": 41.4760,
        "lon": 1.9296,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada",
        "tipos_residuo": "Tratamiento residuos peligrosos + valorización",
        "web": "https://www.atlasgestion.com",
    },
    {
        "nom": "Reciclajes Dolaf",
        "razon_social": "RECICLAJES DOLAF, SL",
        "nif": "B43436518",
        "poblacio": "REUS",
        "comarca": "Baix Camp",
        "lat": 41.1556,
        "lon": 1.1064,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Chatarra + metales no férricos + papel/cartón",
        "web": "https://reciclajesdolaf.com",
    },
    {
        "nom": "GRC Catalana (Gestió Residus Catalunya)",
        "razon_social": "GESTIÓ DE RESIDUS CATALANA, SL",
        "nif": "B60859196",
        "poblacio": "MOLINS DE REI",
        "comarca": "Baix Llobregat",
        "lat": 41.4136,
        "lon": 2.0166,
        "ambit": "Cataluña",
        "categoria": "ESP",
        "tipo": "comercial_privada",
        "tipos_residuo": "Recogida + transporte + intermediación residuos",
        "web": "",
    },
    {
        "nom": "Suez Recycling and Recovery España",
        "razon_social": "SUEZ RECYCLING AND RECOVERY ESPAÑA, SLU",
        "nif": "B83040907",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Recuperación + reciclaje industrial integral",
        "web": "https://www.suez.es",
    },
    {
        "nom": "Tractament Vinyals (chatarra Cataluña central)",
        "razon_social": "TRACTAMENT VINYALS, SL",
        "nif": "B65478169",
        "poblacio": "MANRESA",
        "comarca": "Bages",
        "lat": 41.7235,
        "lon": 1.8267,
        "ambit": "Cataluña",
        "categoria": "RUN",
        "tipo": "comercial_privada",
        "tipos_residuo": "Chatarra + metales no férricos",
        "web": "",
    },
    {
        "nom": "Recyclia (RAEE pilas)",
        "razon_social": "FUNDACIÓN ECOLEC / RECYCLIA",
        "nif": "G83441600",
        "poblacio": "BARCELONA",
        "comarca": "Barcelonès",
        "lat": 41.3851,
        "lon": 2.1734,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "scrap",
        "tipos_residuo": "RAEE + pilas + bombillas (LER 1602xx, 2001xx)",
        "web": "https://www.ecolec.es",
    },
    {
        "nom": "Sumitomo Heavy Industries (Reciclaje aceites)",
        "razon_social": "SUMITOMO HEAVY INDUSTRIES IBERIA, SL",
        "nif": "B66215214",
        "poblacio": "EL PRAT DE LLOBREGAT",
        "comarca": "Baix Llobregat",
        "lat": 41.3270,
        "lon": 2.0951,
        "ambit": "España",
        "categoria": "ESP",
        "tipo": "comercial_privada_multinacional",
        "tipos_residuo": "Aceites usados + lubricantes",
        "web": "",
    },
]


def get_gestoras_comerciales_df():
    """Devuelve el diccionario como DataFrame polars compatible con
    el schema de rgpgrc_geocoded.parquet (oid, nom, poblacio, ambit_territorial,
    categoria, lat, lon, geo_source)."""
    import polars as pl

    rows = []
    for i, g in enumerate(GESTORAS_COMERCIALES_CAT, start=90000):
        rows.append(
            {
                "oid": str(i),
                "nom": g["nom"],
                "poblacio": g["poblacio"],
                "ambit_territorial": g["ambit"],
                "categoria": g["categoria"],
                "lat": g["lat"],
                "lon": g["lon"],
                "geo_source": "manual_dict",
            }
        )
    return pl.DataFrame(rows)
